### ISSUE TITLE
顶部导航栏 logo 春菜应该从 5 种中随机显示一种

### ISSUE THREAD

**Issue by Ayase-252** [bangumi/frontend#101]
![Screen Shot 2022-06-22 at 00 10 41](https://user-images.githubusercontent.com/6264033/174847195-6367e014-fffd-4c62-b744-78bb43965691.png)

设计稿：https://www.figma.com/file/jW61odhQl5lZzhY4CqvvSF/Web-Page?node-id=16%3A450

**Comment by shadowdreamer** [comment]
这几个svg图片怎么分离出来成单独的

**Comment by Ayase-252** [comment]
可以去 slack 里找下大佬
