### ISSUE TITLE
build: svg icon 雪碧图

### ISSUE THREAD

**Issue by Ayase-252** [bangumi/frontend#108]
小 icon 越来越多了，可能影响加载效果。

**Comment by hqxczjx** [comment]
这个搜了下现成的npm包，适合vite的使用下载量比较多的只有 [vite-plugin-svg-icons](https://www.npmjs.com/package/vite-plugin-svg-icons)，这个包目前发现有些bug，而且作者似乎已经没维护了
所以我想到有两种方案，一是把他这个包搞到本地然后对发现的bug进行修复（github上有人提过PR，但是没合）再本地引用。二是自己重新写过一个vite插件，不知道哪种比较适合

**Comment by trim21** [comment]
在 #132 里讨论了一下，感觉我可能理解错这个 issue 的意思了。现在的svg/PNG等等图片资源需要额外的HTTP请求去加载吗？

**Comment by Ayase-252** [comment]
SVG 已经嵌入 JS 就没有多请求问题了
