### ISSUE TITLE
design 包运行错误

### ISSUE THREAD

**Issue by FoundTheWOUT** [bangumi/frontend#120]
#### 环境
os: win11 22h2
node: 16.14.2
pnpm: 7.12.1

#### `pnpm i` && `pnpm design:doc` 出错

<img width="1615" alt="image" src="https://user-images.githubusercontent.com/47922588/193444803-b64f615d-cc29-49ba-bbcb-c85b00ba829e.png">

1. 根据 https://github.com/storybookjs/builder-vite/issues/55 ，`builder-vite` 应该还无法在 pnpm 完美运行，需要解决幽灵依赖问题。
2. `tsconfig.json` 是否应位于 design 包根目录（现位于.storybook 是导致上图错误的原因）
3.  https://github.com/bangumi/frontend/blob/7f94311dd990cd24f778e2acd7143e4649a8a9dd/packages/design/.storybook/tsconfig.json#L3 配置疑似错误，`module` 选项应为 `compilerOptions` 的子选项

❓但根据 https://github.com/bangumi/frontend/pull/106 里的信息，文档是成功构建的，这中间发生了什么...

#### 另外关于根 `tsconfig.json` 的问题
https://github.com/bangumi/frontend/blob/7f94311dd990cd24f778e2acd7143e4649a8a9dd/tsconfig.json#L25
依然是幽灵依赖问题，该 `types` 在项目中非显示依赖，pnpm 没有[shamefully-hois](https://pnpm.io/npmrc#shamefully-hoist)时会报错

**Comment by cokemine** [comment]
有点奇怪。
我在本地以及刚才在 Docker node:14 新环境下 `pnpm design:doc` 是正常的

**Comment by FoundTheWOUT** [comment]
虽然觉得和 node 版本没什么关系，但我还是用14测试了一下，还是有问题。

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/47922588/193446458-77599c8e-b947-4780-bf64-70d21543b8d4.png">

👆这个错误就是最原始的错误（即什么也不动，只拷贝项目），原因就是上面说的第一点，`builder-vite` 的问题。
解决依赖问题后就会出现我第一条留言里截图的错误。

我的猜测是，这个项目一开始不是使用 pnpm 进行依赖管理的，后来改成了 pnpm，但你的 node_modules 依然是旧的目录结构，所以没有问题（估计 vercel 的机器中的缓存，也是构建没有问题的原因）。https://github.com/bangumi/frontend/pull/4 这个PR貌似就是做了这件事。

或许你本机可以删除 node_modules 然后再试一下，但为什么 docker 中能跑就有点奇怪了

**Comment by cokemine** [comment]
我试着删除 node_modules 重新 `pnpm install` 但还是没有复现....
docker 里也是全新的环境。

**Comment by FoundTheWOUT** [comment]
这么奇怪的吗，看看你项目里 node_modules 的目录结构？

**Comment by FoundTheWOUT** [comment]
进一步测试了几个环境，都是使用的 node14，pnpm 7.12.1
✅docker
❌Ubuntu(wsl)
❌window

**Comment by cokemine** [comment]
把全局安装的 ts-node 删掉试试

**Comment by cokemine** [comment]
.storybook 里的 tsconfig 确实有问题。但不知道为什么能正常工作......

根目录依赖有 @testing-library/jest-dom 吧https://github.com/bangumi/frontend/blob/7f94311dd990cd24f778e2acd7143e4649a8a9dd/package.json#L41

**Comment by FoundTheWOUT** [comment]
我全局并没有安装 ts-node，但后来再看了一下是全局的 vercel 有依赖，它安装了 ts-node。我把 vercel 删除后确实解决了问题。下回 vercel 后问题复现，但在包的根目录下添加 tsconfig 就又解决了，感觉是由于包的根目录缺少配置，pnpm 不知道 fallback 到哪个配置去了。

> 根目录依赖有 @testing-library/jest-dom 吧

是有依赖，但没有其类型依赖，这个库的类型依赖在 [@types/testing-library__jest-dom](https://www.npmjs.com/package/@types/testing-library__jest-dom)，而不在自身库里，使用 pnmp 的话需要指定显示依赖，不然 `testing-library__jest-dom` 不在 `node_modules/@types` 里，而是在 `node_modules/.pnpm` 里，这导致 tsconfig 拿不到类型

**Comment by cokemine** [comment]
可以证实这两个问题确实存在。
第一个问题应该涉及安装 ts-node 的问题。虽然 bangumi/frontend 没有依赖或间接依赖到 ts-node，但看起来全局安装 ts-node 或有其依赖的包也有可能会出现问题（我尝试在 docker 下全局安装 ts-node 或是 vercel 但是并没有问题）
https://github.com/storybookjs/storybook/issues/19192
第二个是 pnpm 从 v6 升级到 v7 后依赖处理的规则变了。我试了下 pnpm v6 对于 @types 的包是全都在 node_modules/@types 目录下的。
因为 CI 一直用的是 pnpm v6 所以 tsc 没有报错。。。
https://github.com/bangumi/frontend/blob/7f94311dd990cd24f778e2acd7143e4649a8a9dd/.github/workflows/build.yml#L20
应该添加 @types/testing-library__jest-dom 到 devDependency

cc @FoundTheWOUT 感谢提出了这两个问题。你可以创建两个 PR 来修复这两个问题吗。 tsconfig 和 @types/testing-library__jest-dom 的依赖问题

**Comment by cokemine** [comment]
好像有很多包都像 testing-library/jest-dom 一样直接把 @types/xxx 作为自己的依赖。。那看起来还是把所有的 types hoist 比较好
https://github.com/pnpm/pnpm/issues/4920#issuecomment-1225961351

**Comment by FoundTheWOUT** [comment]
有点神奇，今天再对一个问题进行测试的时候，报错居然消失了。现在怎样都复现不了问题，也不知道是什么情况，所以暂时就不提PR了
