### ISSUE TITLE
website: 登录失败后应该重置 hcaptcha 的状态

### ISSUE THREAD

**Issue by Ayase-252** [bangumi/frontend#224]
如果在完成 hcaptcha 的状态的情况下登录失败（如错误的密码），再次输入正确的密码会提示 hcaptcha 无效。应该在登录失败的时候重置 hcaptcha，让用户重新完成验证。

**Comment by trim21** [comment]
这个我已经做了吧？

**Comment by trim21** [comment]
哦不对，这个我虽然有印象修过，但是没提交到PR里…
