### ISSUE TITLE
Tracking Issue: 发帖/回帖

### ISSUE THREAD

**Issue by trim21** [bangumi/frontend#235]
设计 https://www.figma.com/file/jW61odhQl5lZzhY4CqvvSF/Web-Page?node-id=2165%3A9278&t=zgxJTzwQ91eTTkE5-0

API https://next.bgm.tv/p1/#/default/createNewGroupTopic

https://next.bgm.tv/p1/#/default/createGroupReply

生产环境会污染主站，所以请用stage api进行开发...

- [X] 回帖 https://github.com/bangumi/frontend/pull/256
- [ ] 发帖 https://github.com/bangumi/frontend/pull/320

**Comment by y-young** [comment]
> * 回复成功的时候应该重置文本框的内容，但是这要透穿好几层组件的ref

一般的解决办法是状态提升，让 `Editor` 和 `EditorForm` 变成受控组件，从 topic 页面开始把 reply state 往下传

> * 比较难以把回复增量插入到网页中，要不直接刷新整个网页？

理论上配合 SWR 是可以动态更新的，只要让 data 更新就行了，同样也是使用 SWR 的 mutation

**Comment by trim21** [comment]
> 理论上配合 SWR 是可以动态更新的，只要让 data 更新就行了，同样也是使用 SWR 的 mutation

现在的PR里就是把mutate传下去了...

**Comment by y-young** [comment]
> 现在的PR里就是把mutate传下去了...

突然发现 `postReply` 里已经调了 `mutate` 啊，没有触发 Refetch 吗？

**Comment by trim21** [comment]
issue是在提pr之前写的

**Comment by trim21** [comment]
> > 现在的PR里就是把mutate传下去了...
> 
> 突然发现 `postReply` 里已经调了 `mutate` 啊，没有触发 Refetch 吗？

这三个问题在PR里都解决了，但我react写的不多，但是只是简单地实现了...

**Comment by y-young** [comment]
> 这三个问题在PR里都解决了，但我react写的不多，但是只是简单地实现了...

第一个问题个人习惯上都是改状态提升，尽量避免用Ref，不知道现在这块有没有项目规范

**Comment by trim21** [comment]
> 第一个问题个人习惯上都是改状态提升，尽量避免用Ref，不知道现在这块有没有项目规范

问问其他几位 @bangumi/frontend-collaborators

**Comment by Ayase-252** [comment]
理论上是能不用 ref 就不用。还没仔细看实现

**Comment by cokemine** [comment]
现在既有 onChange={(e) => setContent(e.target.value)} 也有 ref，两个在用一起有点奇怪。或者用 Context？

**Comment by y-young** [comment]
或许可以考虑使用[react-hook-form](https://react-hook-form.com/)，把组件封装做好，之后要实现复杂表单或着加校验的话比较方便

**Comment by trim21** [comment]
> 或许可以考虑使用[react-hook-form](https://react-hook-form.com/)，把组件封装做好，之后要实现复杂表单或着加校验的话比较方便

👀 感兴趣 PR 一下解决这个 issue 吗

**Comment by y-young** [comment]
> 👀 感兴趣 PR 一下解决这个 issue 吗

现在还差什么？有空的话争取……

**Comment by trim21** [comment]
> 现在还差什么？有空的话争取……

我那个 PR 里只是实现了基本功能，根据你们的建议改成比较合适的写法...

**Comment by y-young** [comment]
发帖我在做了，先认领一下
