### ISSUE TITLE
website: 引用没有样式不好区分

### ISSUE THREAD

**Issue by Ayase-252** [bangumi/frontend#249]
![Screenshot 2022-12-17 at 17 56 52](https://user-images.githubusercontent.com/6264033/208236431-bf4a7976-962a-431a-b28f-8be4063e642f.png)

**Comment by y-young** [comment]
大概是加了CSS重置的原因？现在加粗、斜体和下划线也不能正常显示

**Comment by Ayase-252** [comment]
可以看看裁剪下重置样式？

**Comment by y-young** [comment]
我这边看是`font: inherit`给覆盖掉了：
<img width="392" alt="image" src="https://user-images.githubusercontent.com/17172063/208700274-ec14c9ce-7414-4bfc-b7a6-8d5d0e5cb95e.png">

**Comment by trim21** [comment]
合并PR的时候忘记close了
