### ISSUE TITLE
添加 API mock

### ISSUE THREAD

**Issue by Ayase-252** [bangumi/frontend#27]
需要添加 api mock 吗，比如 [msw](https://mswjs.io/)

_Originally posted by @cijiugechu in https://github.com/bangumi/frontend/issues/12#issuecomment-1015510845_

**Comment by ooPG233** [comment]
vite 好像有基于 MockJs 的插件，那个会好一些吗（纯前端新手的提问

**Comment by cijiugechu** [comment]
> vite 好像有基于 MockJs 的插件，那个会好一些吗（纯前端新手的提问

mockjs 没有维护了吧

**Comment by ooPG233** [comment]
> > vite 好像有基于 MockJs 的插件，那个会好一些吗（纯前端新手的提问
> 
> mockjs 没有维护了吧

这样子，谢谢

**Comment by LykorisR** [comment]
MockJs现在不是很好用了，可以换msw或者和后端对接下利用ApiFox这类平台

**Comment by trim21** [comment]
已经在用msw了，issue关掉了。
