### ISSUE TITLE
Bug(website): BBCode渲染有XSS攻击漏洞

### ISSUE THREAD

**Issue by y-young** [bangumi/frontend#275]
看到`RichContent`里用了`dangerouslySetInnerHTML`突发奇想，随手一测还真有问题![image](https://user-images.githubusercontent.com/17172063/209776727-92805380-bb9d-4bfe-9e81-7de1c0f9c89d.png)

https://pr-269-sites--bangumi-next.netlify.app/group/topic/371602#post_2177438

**Comment by cokemine** [comment]
![](https://user-images.githubusercontent.com/17172063/209776727-92805380-bb9d-4bfe-9e81-7de1c0f9c89d.png)

**Comment by trim21** [comment]
果然很dangerous...
