### ISSUE TITLE
test: 考虑引入 e2e 测试

### ISSUE THREAD

**Issue by cijiugechu** [bangumi/frontend#291]
用单测测试一个完整的页面太复杂，依赖和隐式依赖多，是否考虑引入 e2e 测试?

**Comment by Ayase-252** [comment]
e2e 要每次刷新测试环境吧？

**Comment by cijiugechu** [comment]
> e2e 要每次刷新测试环境吧？

playwright 这种貌似不需要吧

**Comment by Ayase-252** [comment]
我指后端环境，需要后端配合吗？

**Comment by cijiugechu** [comment]
> 我指后端环境，需要后端配合吗？

不需要，playwright 可以 mock http response
