### ISSUE TITLE
api返回的命名方式是下划线分隔，在类型定义中是采用驼峰命名还是保证和api一致

### ISSUE THREAD

**Issue by Bubbleioa** [bangumi/frontend#31]
另外发现在 `infobox` 中， `k` 可以没有而只有 `v`
[CharacterID321](https://api.bgm.tv/v0/characters/321#:~:text=%7B%22key%22%3A%22%E5%BC%95%E7%94%A8%E6%9D%A5%E6%BA%90%22%2C%22value%22%3A%5B%7B%22v%22%3A%22anidb.net%22%7D%5D%7D)

**Comment by Ayase-252** [comment]
类型定义中以驼峰命名，保持与其余前端工程代码风格一致。

> 另外发现在 infobox 中， k 可以没有而只有 v
CharacterID321

由于现在没有正式开发，项目中代码只是 demo。正式开发后应该会修。如果感兴趣的话也可以现在提 PR 修。

**Comment by Trim21** [comment]
网页是否可以考虑用一套别的 API，而不一定非要用现在的公共 API？

**Comment by Bubbleioa** [comment]
> 网页是否可以考虑用一套别的 API，而不一定非要用现在的公共 API？

如果给后端带来的额外工作不多的话挺不错的

roadmap 上还有 GraphQL, 之后肯定要改的

**Comment by Trim21** [comment]
> 如果给后端带来的额外工作不多的话挺不错的
> 
> roadmap 上还有 GraphQL, 之后肯定要改的

等有设计了根据需要的数据考虑一下私有 API

**Comment by Ayase-252** [comment]
我看问题解决了，就先 close 了哈。bgm38
