### ISSUE TITLE
design: Typography/Link 依赖问题

### ISSUE THREAD

**Issue by FoundTheWOUT** [bangumi/frontend#313]
现在 [Typography/Link](https://github.com/bangumi/frontend/blob/master/packages/design/components/Typography/Link.tsx) 这个组件依赖了 `react-router-dom`，感觉 design 包只负责样式比较好，业务逻辑在 website 里做就好了

**Comment by y-young** [comment]
你的意思是移到website包还是把逻辑去掉？感觉这个还算可以接受，倒是Topic那块可以考虑移出去，如果不用react-router-dom的话每次用Link都得`router.push`一下太麻烦了

**Comment by FoundTheWOUT** [comment]
为什么要 push，直接写 to 就好了。
> 你的意思是移到website包还是把逻辑去掉？

把逻辑去掉，逻辑移到 website 做

**Comment by y-young** [comment]
> 把逻辑去掉，逻辑移到 website 做

是external link的逻辑还是直接不用RouterLink？我觉得这块不是什么大问题

**Comment by FoundTheWOUT** [comment]
当然是 RouterLink，有问题是因为现在 website 使用的自定义的 Link，不是 react-router-dom 提供的 Link

**Comment by y-young** [comment]
现在没有自定义 Link 了，这个应该就不成问题了吧
