### ISSUE TITLE
feat(wiki): 上传封面

### ISSUE THREAD

**Issue by trim21** [bangumi/frontend#327]
design: https://www.figma.com/file/jW61odhQl5lZzhY4CqvvSF/Web-Page?node-id=3109%3A10750&t=3RdySxIfHWZoRwsG-0

API: 

https://next.bgm.tv/p1/#/wiki/uploadSubjectCover

https://next.bgm.tv/p1/#/wiki/listSubjectCovers

https://next.bgm.tv/p1/#/wiki/voteSubjectCover

目前允许上传 `.webp,.jpg,.jpeg,.png` 后缀名的图片，图片原始大小应该小于4mb

**Comment by FoundTheWOUT** [comment]
> POST https://next.bgm.tv/p1/#/wiki/uploadSubjectCover

content 是指图片的 base64 吗

**Comment by trim21** [comment]
> > POST https://next.bgm.tv/p1/#/wiki/uploadSubjectCover
> 
> content 是指图片的 base64 吗

是

**Comment by trim21** [comment]
现在可以上传webp图片了，会自动转换成jpeg

**Comment by Jan30chen** [comment]
> POST https://next.bgm.tv/p1/#/wiki/uploadSubjectCover

我把图片转为base64字符串，放到content里，swagger里调用一下报了这个错误，是咋回事呢？
我把字符串丢到浏览器里是可以显示的。
```
{
  "statusCode": 500,
  "code": "FST_ERR_FAILED_ERROR_SERIALIZATION",
  "message": "Failed to serialize an error. Error: \"code\" is required!. Original error: body/content must match format \"byte\""
}
```
我把发送的content的前面部分截取一下好了，整个放上来太长了；一个46k的jpge图片
```
{ "content": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2……"}
```

**Comment by trim21** [comment]
没有 `data:image/jpeg;base64,`  这部分

**Comment by trim21** [comment]
> > POST https://next.bgm.tv/p1/#/wiki/uploadSubjectCover
> 
> 我把图片转为base64字符串，放到content里，swagger里调用一下报了这个错误，是咋回事呢？ 我把字符串丢到浏览器里是可以显示的。
> 
> ```
> {
>   "statusCode": 500,
>   "code": "FST_ERR_FAILED_ERROR_SERIALIZATION",
>   "message": "Failed to serialize an error. Error: \"code\" is required!. Original error: body/content must match format \"byte\""
> }
> ```
> 
> 我把发送的content的前面部分截取一下好了，整个放上来太长了；一个46k的jpge图片
> 
> ```
> { "content": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2……"}
> ```

https://next.bgm.tv/demo/subject/184017/upload-cover

**Comment by cijiugechu** [comment]
> 现在可以上传webp图片了，会自动转换成jpeg

webp 感觉不需要转换了，[多数浏览器都支持了](https://caniuse.com/webp)，甚至 safari 都支持一段时间了

**Comment by trim21** [comment]
> > 现在可以上传webp图片了，会自动转换成jpeg
> 
> webp 感觉不需要转换了，[多数浏览器都支持了](https://caniuse.com/webp)，甚至 safari 都支持一段时间了

旧macOS版本不支持

**Comment by trim21** [comment]
> > > 现在可以上传webp图片了，会自动转换成jpeg
> > 
> > 
> > webp 感觉不需要转换了，[多数浏览器都支持了](https://caniuse.com/webp)，甚至 safari 都支持一段时间了
> 
> 旧macOS版本不支持

等有机会统计一下用户UA，看看占比再说了

**Comment by Jan30chen** [comment]
/p1/wiki/subjects/{subjectID}/covers 返回的thumbnail和raw是压缩画质后路径和原始图片路径吗？
在https://dev.bgm38.com/的swagger往184017条目里上传了张图片，返回的路径都打不开，404了

**Comment by trim21** [comment]
> /p1/wiki/subjects/{subjectID}/covers 返回的thumbnail和raw是压缩画质后路径和原始图片路径吗？ 在`https://dev.bgm38.com/`的swagger往184017条目里上传了张图片，返回的路径都打不开，404了

修复了

**Comment by trim21** [comment]
> > 现在可以上传webp图片了，会自动转换成jpeg
> 
> webp 感觉不需要转换了，[多数浏览器都支持了](https://caniuse.com/webp)，甚至 safari 都支持一段时间了

![image](https://user-images.githubusercontent.com/13553903/227702097-eabfd994-f542-4bdb-9382-beca12d1e002.png)

只有这部分用户可能符合 [vite](https://vitejs.dev/guide/build.html#browser-compatibility) 的要求但又[不支持 webp](https://caniuse.com/?search=webp)

**Comment by Ayase-252** [comment]
14-15 还算很新的吧

**Comment by trim21** [comment]
> 14-15 还算很新的吧

safari支持，但是要看macos的版本

**Comment by Jan30chen** [comment]
上传封面的接口传一个1M多的图片，会有413错误`Request Entity Too Large`，看样子是body太大了；
这个是nginx设置的问题还是post请求本身的限制？

**Comment by trim21** [comment]
Nginx的

**Comment by Jan30chen** [comment]
> 你看响应内容是不是Nginx的错误页面？应该是Nginx的，我一会改一下

是的，响应了个Nginx的网页

**Comment by trim21** [comment]
你先用小图片开发（）
