### ISSUE TITLE
Bug: Button 嵌套 Link 时有效点击区域有限

### ISSUE THREAD

**Issue by y-young** [bangumi/frontend#329]
在按钮内的文字区域外点击无效果，如小组概览按钮

关联讨论： #313

**Comment by FoundTheWOUT** [comment]
没理解，这不是可以吗
![20230201_163235](https://user-images.githubusercontent.com/47922588/215991221-b6542f84-2162-4692-8e95-95fcfbd9a8f5.gif)

**Comment by y-young** [comment]
那个是 Tab 不是 Button 吧

![button](https://user-images.githubusercontent.com/17172063/215993114-f065f0e5-6e8c-424a-a9e3-b0e654f5688e.gif)

**Comment by y-young** [comment]
> 正常来说，应该把 Button 放到 Link 里才对

应该是可行的，但在 [这里](https://stackoverflow.com/questions/42463263/wrapping-a-react-router-link-in-an-html-button) 有人提到 `<a>` 里面嵌套 `<button>` 并不是合法的 HTML，我在想不如直接给 Button 加一个参数 `href` 然后用 `navigate`，也不需要配合 Link 了

**Comment by FoundTheWOUT** [comment]
这样啊，难道写这里的时候是考虑到这条规范了吗。我个人倾向于直接给 Link Component 上 style（当然用 navigate 也行

> 我在想不如直接给 Button 加一个参数 href 然后用 navigate

这样的话 Button 不又要依赖 react-router-dom 了吗

**Comment by y-young** [comment]
> 我个人倾向于直接给 Link Component 上 style（当然用 navigate 也行

Button 的样式可以直接用所以不如直接渲染（
用 navigate 唯一的问题是没有 `<a>` 这个元素所以浏览器可能看不到目标链接？

> 这样的话 Button 不又要依赖 react-router-dom 了吗

所以我才关联了之前那个 Issue 啊……不知道为什么 website 要再实现一个 Link，而且 NavLink 也可以用 react-router-dom 的吧？

**Comment by FoundTheWOUT** [comment]
> 不知道为什么 website 要再实现一个 Link

https://github.com/bangumi/frontend/pull/183

**Comment by y-young** [comment]
原来如此，所以现在页面必须等数据加载完才开始渲染是吗？之前习惯了做动态加载，还是第一次遇到这个问题。
有没有可能在 LinkContext 里监听 [navigation.state](https://reactrouter.com/en/main/hooks/use-navigation#navigationstate)，这样就不用手动维护 transition state了？

**Comment by FoundTheWOUT** [comment]
> 有没有可能在 LinkContext 里监听 [navigation.state](https://reactrouter.com/en/main/hooks/use-navigation#navigationstate)，这样就不用手动维护 transition state了？

所以这就是 react-router-dom 它们的方案，我们现在是用不了的。

> This feature only works if using a data router, see [Picking a Router](https://reactrouter.com/en/main/routers/picking-a-router)
