### ISSUE TITLE
design: Form 样式

### ISSUE THREAD

**Issue by FoundTheWOUT** [bangumi/frontend#364]
@y-young 感觉 compact Form 的样式看得有点费劲。我觉得可以按[这里](https://github.com/bangumi/frontend/pull/351#discussion_r1101725896)说的去调下。
现在的话看起来是 Input 的样式由 Form 的 compact 模式注入进来的类名而发生了变化，Form 不应该去处理后代的样式，Form 提供状态就好了，后代在 compact 里长什么样应该它自己去处理，如果有重复的样式可以考虑抽离出来。这样处理的好处是如果新增样式和组件自己的样式发生了冲突，我们可以在组件自己的样式文件里进行调整。另外 `useInFormContext` 也不太必要，靠 css 是完全足够的，也是清晰的。
具体可以看下 `design/Select` 和 `design/Input.Group` 的关系。

**Comment by y-young** [comment]
现在的已经是按 [这里](https://github.com/bangumi/frontend/pull/351#discussion_r1101725896) 说的调整过了，参照 https://en.bem.info/methodology/block-modification/#using-a-mix-to-change-a-block 做的
按 `design/Select` 和 `design/Input.Group` 的关系意思是在 Input 和 EditorForm 里写 `.bgm-form--compact .bgm-input` 这样的选择器？我以为这样也是不符合 BEM 规范的，因为我也不是很了解 BEM 规范，还是请 @Ayase-252 来评判
此外对于 `.bgm-form-item:not(:first-of-type)` 的样式如果分散到 Input 和 Editor 里写还会出现重复的情况？

**Comment by FoundTheWOUT** [comment]
🤔为什么需要考虑 `bgm-form-item` 的样式，你没用到这个 label 不是应该不写这个 <Form.Item> 吗，现在 Input 发生样式变化是和 Form campact 有关，和 form item 没关系吧

**Comment by y-young** [comment]
> 🤔为什么需要考虑 `bgm-form-item` 的样式，你没用到这个 label 不是应该不写这个 <Form.Item> 吗，现在 Input 发生样式变化是和 Form campact 有关，和 form item 没关系吧

之前是考虑让到 Form 各种状态下的使用方法一致，比如让一个普通 Form 可以直接变成 compact，不写 FormItem 的话确实就没这个问题了，但是上下边框的样式如果不在 Form 里还会重复写吧（除非用 mixin）

**Comment by FoundTheWOUT** [comment]
> 按 design/Select 和 design/Input.Group 的关系意思是在 Input 和 EditorForm 里写 .bgm-form--compact .bgm-input 这样的选择器？我以为这样也是不符合 BEM 规范的

这个和 BEM 规范没太大关系，只是一个布局技巧。
![image](https://user-images.githubusercontent.com/47922588/218695148-afa4e867-6f27-4a9e-a480-848d1b2e6686.png)
![image](https://user-images.githubusercontent.com/47922588/218695189-241f4431-a0d8-48f3-b563-529a765a2ceb.png)
更高的 Selector 优先级覆盖掉原先的样式，且写在一个文件里可以让大家明白在什么时候这个组件自己发生了变化，而不是别的地方修改了它的样式。
如果你把上面的 bgm-select 写成 bgm-select--group，那也许会更有 BEM 味，但结果也是一样的，原因是这里的 Selecor 更高，会覆盖掉 bgm-select。

> 重复写

有需要时 mixin 就好了

> 比如让一个普通 Form 可以直接变成 compact

😂，`bgm-form-item` 本身就是 styleless，它只控制 label 样式和宽度。如果你想让普通 Form 直接变成 compact 那不还是和 `bgm-form-item` 没关系吗，只和有 style 的元素有关，比如 Input、Editor 这些。有关系的就 bgm-form 的 gap
