### ISSUE TITLE
design：添加更多toast样式

### ISSUE THREAD

**Issue by trim21** [bangumi/frontend#420]
![image-2](https://user-images.githubusercontent.com/13553903/221201055-b42ab252-127e-4c88-a6e3-1a062b0b906d.png)

slack里面提到把登录页面的错误提示提取为公共组件

感觉可以为toast添加不同的类型，如info/error（甚至warning），用这个作为error toast的显示效果。info toast则继续用现在灰色的效果。

比如用于显示比如400/401相应中的错误信息。

@vistaing

**Comment by Jan30chen** [comment]
目前的toast是作为弹出层出现的，登录页面的错误提示是作为页面元素出现的；具体以哪种为准呢？这个要请设计重新设计下吗

**Comment by trim21** [comment]
> 目前的toast是作为弹出层出现的，登录页面的错误提示是作为页面元素出现的；具体以哪种为准呢？这个要请设计重新设计下吗

添加一个纯样式的组件在页面和toast里分别使用？

**Comment by Jan30chen** [comment]
> 

把ErrorMeesge提成了Message组件，目前只分了info和error类型，更多warn之类的类型需要的话再加；
然后把Toast组件里的纯文本换成了message:info组件，可能之后也要将toast分类型，不过目前现在先这样吧。
需要现在合并掉吗，还是等再讨论完善一下？

**Comment by Jan30chen** [comment]
> > 目前的toast是作为弹出层出现的，登录页面的错误提示是作为页面元素出现的；具体以哪种为准呢？这个要请设计重新设计下吗
> 
> 添加一个纯样式的组件在页面和toast里分别使用？


把ErrorMeesge提成了Message组件，目前只分了info和error类型，更多warn之类的类型需要的话再加；
然后把Toast组件里的纯文本换成了message:info组件，可能之后也要将toast分类型，不过目前现在先这样吧。
需要现在合并掉吗，还是等再讨论完善一下？

**Comment by trim21** [comment]
> 如果是做 Toast 的话，一共涉及到几种类别的信息叻？

暂时想到的就info和error两种吧？用现成的组件就行

**Comment by trim21** [comment]
> > 如果是做 Toast 的话，一共涉及到几种类别的信息叻？
> 
> 暂时想到的就info和error两种吧？用现成的组件就行

可能还有warning，但是目前还没想到有啥使用场景
