### ISSUE TITLE
Bug: 应动态设置页面标题

### ISSUE THREAD

**Issue by y-young** [bangumi/frontend#438]
每个页面应该设置不同的标题

不知道除了 [react-helmet](https://github.com/staylor/react-helmet-async) 之外还有没有更好的办法？

**Comment by cokemine** [comment]
如果只改 title 可以只在 useEffect 改 document.title

**Comment by y-young** [comment]
> 如果只改 title 可以只在 useEffect 改 document.title

不能每个地方都写一遍吧，得封装一下

**Comment by cokemine** [comment]
对，可以封装成一个 hook

**Comment by Ayase-252** [comment]
helmet 也行吧，不知道以后会不会有定制 head 内 tag 的场景

**Comment by y-young** [comment]
> helmet 也行吧，不知道以后会不会有定制 head 内 tag 的场景

现在不同页面会有不同的 meta title 和 meta description 之类的，为了 SEO 的话也是需要的吧

> 但为啥这不是原始的 [react-helmet](https://github.com/nfl/react-helmet)?

这个貌似不维护了……

**Comment by trim21** [comment]
收到通知时给标题加上一个 `(n) ...` 的前缀
