### ISSUE TITLE
没有 `to` 的情况下登陆成功后页面不会转跳

### ISSUE THREAD

**Issue by trim21** [bangumi/frontend#480]
https://github.com/bangumi/frontend/pull/359

@y-young

**Comment by trim21** [comment]
好像弄错了，没法复现了

**Comment by trim21** [comment]
不是弄错了，的确有这个问题，但是不确定怎么才能复现 🤔

**Comment by y-young** [comment]
应该是输错一次密码后，貌似重置验证码的时候会把 history 覆盖掉

**Comment by trim21** [comment]
> 另外密码尝试次数在输入正确密码后也不会重置的吗b38

正常是应该重置的，偷懒没写。

**Comment by trim21** [comment]
> 应该是输错一次密码后，貌似重置验证码的时候会把 history 覆盖掉
> 
> 另外密码尝试次数在输入正确密码后也不会重置的吗b38

是影响开发了吗，我加一下吧。
