### ISSUE TITLE
网站字体与使用问题

### ISSUE THREAD

**Issue by Ayase-252** [bangumi/frontend#58]
现 figma 设计稿上使用字体：

```
font-family: 'Source Han Sans SC';
```

网站上现使用字体：

```
font-family: 'Noto Sans SC',
system-ui, -apple-system, BlinkMacSystemFont,
Arial, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif;
```

老 bgm 使用字体：

```
font-family: 'SF Pro SC','SF Pro Display','PingFang SC','Lucida Grande','Helvetica Neue',Helvetica,Arial,Verdana,sans-serif,"Hiragino Sans GB"
```

这个 issue 主要讨论解决使用什么字体，然后如何使用？ Web Font 应该不太行，感觉会连接会有一定问题

**Comment by Sai** [comment]
在原来基础上加上
system-ui, -apple-system, BlinkMacSystemFont
和
Microsoft YaHei
作为基础字体

`font-family: 
system-ui, -apple-system, BlinkMacSystemFont,
'SF Pro SC','SF Pro Display','PingFang SC','Microsoft YaHei','Lucida Grande','Helvetica Neue', 'Segoe UI ', Helvetica,Arial,Verdana,sans-serif`

**Comment by Ayase-252** [comment]
看来是使用原来字体大方向了

**Comment by cokemine** [comment]
设计上 Copyright 的部分字体指定成了 `Roboto` 这个字体，这个也要去掉 Web Font 按照默认的加载吗

**Comment by Sai** [comment]
设计稿会用某个平台的字体出图，但实际上显示是根据具体平台的。

**Comment by vistaing** [comment]
> 在原来基础上加上 system-ui, -apple-system, BlinkMacSystemFont 和 Microsoft YaHei 作为基础字体
> 
> `font-family: system-ui, -apple-system, BlinkMacSystemFont, 'SF Pro SC','SF Pro Display','PingFang SC','Microsoft YaHei','Lucida Grande','Helvetica Neue', 'Segoe UI', Helvetica,Arial,Verdana,sans-serif`

关于设计稿内的字体使用，不好意思没有跟各位沟通好，实际的字体使用确实遵循 Sai 提出的方式，设计稿之后会统一为方便我操作的系统默认字体，示意

**Comment by Ayase-252** [comment]
Fixed #61
