### ISSUE TITLE
[bug report] 登录密码提示错误

### ISSUE THREAD

**Issue by eczn** [bangumi/frontend#598]
https://next.bgm38.com/p1/login 这个接口持续报这个
<img width="527" alt="image" src="https://github.com/bangumi/frontend/assets/13131724/2667ae80-3b23-4b76-b916-91d12f394235">

入参类似下面，密码确认过没问题，在主站点可以登录 https://bangumi.tv
<img width="695" alt="image" src="https://github.com/bangumi/frontend/assets/13131724/7abb0b02-e335-4317-9628-85222e54ab4c">

**Comment by trim21** [comment]
bgm38是测试站点，和主站的数据不一样
