### ISSUE TITLE
website: header 登录按钮应该有 hover 态

### ISSUE THREAD

**Issue by Ayase-252** [bangumi/frontend#90]
![Screen Shot 2022-06-06 at 22 57 51](https://user-images.githubusercontent.com/6264033/172186985-2478eb63-b134-49f7-9cf4-4c0c6775cb75.png)

![Screen Shot 2022-06-06 at 22 57 09](https://user-images.githubusercontent.com/6264033/172186899-1328f01d-d746-49b9-87b4-13ad07ce1585.png)

Refs: https://www.figma.com/file/jW61odhQl5lZzhY4CqvvSF/Web-Page?node-id=1376%3A5181

**Comment by shadowdreamer** [comment]
我弄了下
